version: '3.7'

services:
  backend-api:
    build:
      ./backend-api-2/simple-api-main/simple-api/ #chemin vers dockerfile
    networks:
      - my-network
    depends_on:
      - postgres  # demarre après postgres
  postgres:
    build:
      ./postgres/
    networks:
      - my-network
    volumes:
      - db-volume:/var/lib/postgresql/data

  httpd:
    build:
      ./http_basic/ #chemin vers dockerfile
    ports:
      - 80:80
    networks:
      - my-network
    depends_on:
      - backend-api # demarre après backend-api
networks:
  my-network:
volumes:
  db-volume: {}