name:  CI  devops  2022  CPE
on:
  # tests branches
  push:
    branches:
      - main
      - develop
  pull_request:
jobs:
  test-backend:
    runs-on:  MacOS 12.2
    steps:
      #checkout your github code using actions/checkout@v2.3.3  
      - uses: actions/checkout@v2.3.3
      - name:  Set  up  JDK  11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      #Run and verification with maven of pom.xml location
      - name:  Build  and  test  with  Maven
        run:  mvn -B verify --file APIJava/simple-api/pom.xml
  build-and-push-docker-image:
    needs: test-backend
    # run only when code is compiling and tests are passing
    runs-on: MacOS 12.2
    # steps to perform in job
    steps:
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{secrets.DOCKERHUB_TOKEN}}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
        # relative path to the place where source code with Dockerfile is located
          context: ./APIJava/simple-api
        # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKERHUB_USERNAME}}/APIJava
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Build image and push database
        uses: docker/build-push-action@v2
        with:
          context: ./postgres
          tags: ${{secrets.DOCKERHUB_USERNAME}}/postgres
          push: ${{ github.ref == 'refs/heads/main' }}
      - name: Build image and push httpd
        uses: docker/build-push-action@v2
        with:
          context: ./http_basic
          tags: ${{secrets.DOCKERHUB_USERNAME}}/http_basic
          push: ${{ github.ref == 'refs/heads/main' }}
  test-backend:
    runs-on:  MacOS 12.2
    steps:
      #checkout your github code using actions/checkout@v2.3.3  
      - uses: actions/checkout@v2.3.3
      #do the same with another action (actions/setup-java@v2) that enable to setup jdk 11  
      - name:  Set  up  JDK  11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      #finally build your app with the latest command  
      - name:  Build  and  test  with  Maven
        run:  mvn -B verify sonar:sonar -Dsonar.projectKey=mootea_devopsS82022CPELyon -Dsonar.organization=mootea -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{secrets.SONAR_TOKEN}} --file APIJava/simple-api-main/simple-api/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  env:
    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    working-directory: ./APIJava/simple-api-main/simple-api